# Generated by Django 4.2.9 on 2024-04-03 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='heading',
            new_name='title',
        ),
    ]
