# Generated by Django 4.2.9 on 2024-04-27 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_rename_name_long_organisation_name_full_and_more'),
        ('news', '0004_alter_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('patronimic_name', models.CharField(max_length=100)),
                ('contract_number', models.CharField(max_length=50)),
                ('contract_date', models.DateField()),
                ('message', models.TextField()),
                ('send_to_email', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.organisation')),
            ],
        ),
    ]
