# Generated by Django 4.2.9 on 2024-01-14 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование', max_length=50, verbose_name='Наименование компание')),
                ('description', models.TextField(help_text='Введите описание', max_length=1000, verbose_name='Описание компании')),
                ('typ', models.CharField(choices=[('Ломбард', 'Ломбард')], help_text='Выберите тип', max_length=255, verbose_name='Наименование типа')),
                ('image', imagekit.models.fields.ProcessedImageField(help_text='Загрузите изображение', upload_to='product_images/', verbose_name='Основное изображение')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['id'],
            },
        ),
    ]
