# Generated by Django 4.2.9 on 2024-05-03 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_rename_name_long_organisation_name_full_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisationtype',
            options={'ordering': ['name'], 'verbose_name': 'Тип организации', 'verbose_name_plural': 'Типы организаций'},
        ),
        migrations.AlterModelOptions(
            name='productclass',
            options={'ordering': ['name'], 'verbose_name': 'Класс продукта (заем\\инвестиции)', 'verbose_name_plural': 'Классы продуктов (заем\\инвестиции)'},
        ),
        migrations.AlterField(
            model_name='filial',
            name='location_fact',
            field=models.CharField(max_length=500, verbose_name='Фактическое метоположение филиала'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='inn',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(10)], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='location_reg',
            field=models.CharField(max_length=550, verbose_name='Место регистрации организации'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='ogrn',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.MaxLengthValidator(13), django.core.validators.MinLengthValidator(13)], verbose_name='ОГРН'),
        ),
    ]
