# Generated by Django 4.2.9 on 2024-05-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_organisationtype_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='term',
        ),
        migrations.AddField(
            model_name='product',
            name='term_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Срок в днях, максимальный'),
        ),
        migrations.AddField(
            model_name='product',
            name='term_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Срок в днях, минимальный'),
        ),
    ]
